import 'dart:math';

/*Exercise 11
Write a program that takes a list of numbers for example

a = [5, 10, 15, 20, 25]
and makes a new list of only the first and last elements of the given list. For practice, write this code inside a function.  */
void main() {
  final random = Random();
  List<int> randomList = List.generate(10, (_) => random.nextInt(100));

  // pass it to the  function
  print('Random List Generated by the inBuilt function $randomList');
  print('Initial and Last element of a List :');
  print(newList(randomList));
}

// Function that returns the first and last element of a List
List<int> newList(List<int> initialList) {
  return [initialList.first, initialList.last];
}
